title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using the plugin? We're here to help!

        **Before asking**: Please check the [README](../../blob/main/README.md) and existing discussions first.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I've checked the README.md
          required: true
        - label: I've searched existing discussions for similar questions
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: "Select the area most related to your question"
      options:
        - Installation and setup
        - Slash commands (/rails-team, /rails-db, etc.)
        - Specialist behavior (DHH, routing, Active Record, Hotwire, etc.)
        - Configuration (rails-expert.local.md)
        - Plugin structure
        - Skills (creation, triggering)
        - Agents (creation, AI generation)
        - Hooks (events, prompt-based)
        - MCP integration
        - Marketplace creation
        - Troubleshooting
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: "What would you like to know?"
      placeholder: "How do I...? Why does...? Can I...?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: "Any relevant details about your setup or use case"
      placeholder: "I'm trying to..."
    validations:
      required: false

  - type: input
    id: claude-code-version
    attributes:
      label: Claude Code Version (for troubleshooting)
      description: "Run `claude --version` to find this"
      placeholder: "e.g., 2.0.74"
    validations:
      required: false

  - type: dropdown
    id: ide
    attributes:
      label: IDE / Editor
      description: "Which editor or environment are you using?"
      options:
        - Terminal (CLI only)
        - VS Code
        - JetBrains (IntelliJ, WebStorm, etc.)
        - Vim / Neovim
        - Cursor
        - Windsurf
        - Zed
        - Other
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: "Select your operating system"
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: false
