name: Documentation Improvement
description: Suggest improvements to documentation (README, CLAUDE.md, or plugin docs)
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear documentation helps everyone use the plugin more effectively.

  - type: dropdown
    id: doc-type
    attributes:
      label: Which documentation needs improvement?
      options:
        - README.md
        - CLAUDE.md
        - CHANGELOG.md
        - Command documentation (/rails-team, /rails-db, etc.)
        - Skill documentation (rails-routing, rails-active-record, etc.)
        - Agent documentation (DHH coordinator, specialists)
        - Code of Conduct
        - Contributing guidelines
        - LICENSE
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Specific Location
      description: File path or section name
      placeholder: "e.g., README.md - Installation section, plugins/rails-expert/skills/rails-routing/SKILL.md"

  - type: textarea
    id: issue
    attributes:
      label: What's unclear or missing?
      description: Describe what's confusing, incorrect, or missing
      placeholder: The documentation doesn't explain...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve it? (Feel free to include proposed wording)
      placeholder: It would be clearer if...

  - type: checkboxes
    id: issue-type
    attributes:
      label: Type of issue
      options:
        - label: Incorrect information
        - label: Missing information
        - label: Unclear explanation
        - label: Code example needed
        - label: Broken link
        - label: Missing link (should link somewhere but doesn't)
        - label: Typo or grammar
        - label: Outdated content
        - label: Other

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or relevant information
