name: Question or Support
description: Ask a question about using the rails-expert plugin
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using the plugin? We're here to help!

        **💡 Consider using [GitHub Discussions](https://github.com/sjnims/rails-expert/discussions) instead!**
        Questions often get faster community responses there, and help others with similar questions find answers.

        **Before asking**: Please check the [README](https://github.com/sjnims/rails-expert/blob/main/README.md) and [CLAUDE.md](https://github.com/sjnims/rails-expert/blob/main/CLAUDE.md) first.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...? Why does...? Can I...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      options:
        - Installation and setup
        - Slash commands (/rails-team, /rails-db, etc.)
        - Specialist behavior (DHH, routing, Active Record, Hotwire, etc.)
        - Configuration (rails-expert.local.md)
        - Skill development
        - Agent development
        - Hook development
        - MCP integration
        - Marketplace setup
        - Troubleshooting
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: What steps have you already taken to solve this?
      placeholder: "I've tried... I looked at..."

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or relevant information
      placeholder: "I'm trying to... My use case is..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I've checked the README.md
          required: true
        - label: I've searched existing issues and discussions
          required: true
        - label: I've considered posting in GitHub Discussions instead
          required: true
        - label: This is a question, not a bug report or feature request
          required: true
